### ISSUE TITLE
Provide insertions client GUI option 

### ISSUE THREAD

**Issue by donJoseLuis** [bozturkMSFT/insertions-client#33]
My first code drop of the tool started as a simple 2 parameter command line.  Now boasting support for 9 input parameters; some of which with dependency with others.

Until the insertions client codebase is integrated into a fully automated VS insertions process, a GUI option may make life easier for tool users.

![image](https://user-images.githubusercontent.com/58810449/81467164-2a2fe700-91d7-11ea-819e-7c29bdf8bfa0.png)

**Comment by donJoseLuis** [comment]
@bozturkMSFT let's discuss this week what we want to do in this case.

**Comment by bekir-ozturk** [comment]
Copy/pasting my https://github.com/bozturkMSFT/insertions-client/pull/34#issuecomment-630088049 from the related PR.

Besides the points @ladipro mentioned, I have the following concerns:
- This is a Windows-Only piece of code. We will either need to run CI/CD builds only on pools with Windows machines, or we will need to do some tricks to exclude this project and related tests when building on other operating systems.
- We may not have the availability to update the GUI as frequently as we update the core, which will prevent the code from compiling. Instead of adding a direct reference to the core cs project, we can reference it as a nuget package with a specific version. And since both projects are maintained and versioned at their own pace, having a separate repo for the GUI part sounds like the right thing to do to me.

I am closing this for now until we have better justification for this change. We can then discuss the proper place of enlistment and the appropriate way of referencing the core.

Please feel free to reopen if you wish to discuss further.
